"""query logs

Revision ID: 0003_query_logs
Revises: 0002_documents
Create Date: 2026-07-11 07:03:49.364696
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_query_logs'
down_revision: str | None = '0002_documents'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('grounded_ratio', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('took_ms', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_query_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_logs'))
    )
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_logs_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_query_logs_needs_review'))

    op.drop_table('query_logs')
    # ### end Alembic commands ###
