"""review workflow

Revision ID: 0006_review
Revises: 0005_evals
Create Date: 2026-07-11 12:14:15.004378
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_review'
down_revision: str | None = '0005_evals'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='review_status', native_enum=False, create_constraint=True, length=20), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_query_logs_review_status'), ['review_status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_query_logs_reviewed_by_users'), 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_query_logs_reviewed_by_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_query_logs_review_status'))
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
